##### Terminal #####

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

##### History #####

set -g history-limit 100000

##### Escape #####

set -sg escape-time 10

##### Mouse #####

set -g mouse on

##### Index #####

set -g base-index 1
setw -g pane-base-index 1

##### Renumber #####

set -g renumber-windows on

##### Focus #####

set -g focus-events on

##### Clipboard #####

set -g set-clipboard on

##### Vim #####

setw -g mode-keys vi

##### Activity #####

setw -g monitor-activity on
set -g visual-activity off
