set -g status-left-length 30
set -g status-right-length 80

set -g status-left "#S"

set -g status-right "#{?client_prefix,⌨ ,} %Y-%m-%d %H:%M "

setw -g window-status-current-format "#I:#W"

setw -g window-status-format "#I:#W"
